# Generated by Django 4.2.11 on 2024-05-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('Descripcion', models.TextField()),
                ('M2_construidos', models.FloatField()),
                ('M2_totales', models.FloatField()),
                ('Cantidad_estacionamientos', models.IntegerField()),
                ('Cantidad_habitaciones', models.IntegerField()),
                ('Cantidad_banos', models.IntegerField()),
                ('Direccion', models.CharField(max_length=255)),
                ('Comuna', models.CharField(max_length=100)),
                ('Tipo_inmueble', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('parcela', 'Parcela')], max_length=20)),
                ('Precio_mensual_arriendo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('RUT', models.CharField(max_length=12, unique=True)),
                ('Direccion', models.CharField(max_length=255)),
                ('Telefono', models.CharField(max_length=15)),
                ('Correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('Tipo_usuario', models.CharField(choices=[('arrendatario', 'Arrendatario'), ('arrendador', 'Arrendador')], max_length=20)),
            ],
        ),
    ]
