# Generated by Django 4.2.11 on 2024-05-17 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_inmuebles', '0004_region_comuna_alter_inmueble_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='comuna',
            field=models.ForeignKey(db_column='comuna_id', on_delete=django.db.models.deletion.CASCADE, to='registro_inmuebles.comuna'),
        ),
    ]
