# Generated by Django 4.2.11 on 2024-05-20 20:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registro_inmuebles', '0006_alter_inmueble_comuna'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_form_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=64)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Reg', 'verbose_name_plural': 'Regiones'},
        ),
    ]
